
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ewpiurahimluabchtvvk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV3cGl1cmFoaW1sdWFiY2h0dnZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4NjE5MzMsImV4cCI6MjA1OTQzNzkzM30.RbDPJP1VHeBpDB-8LnsoNuzmBwn4q8AeyNJ8nVGm8GA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
